#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#########################################################################
# Author: Johnny Shi
# Created Time: 2018-09-02 00:16:58
# File Name: start.py
# Description:
#########################################################################
import sys

if len(sys.argv) > 1:
    words = sys.argv[1:]
    words[0] = words[0].replace('.', '')
    print('vim ' + '_'.join(words) + '.py')

# vim: set expandtab ts=4 sts=4 sw=4 :
